#
# Copyright (C) 2023 Geonames API.
#
# Geonames API is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: "3"

services:
  geonames-os:
    image: opensearchproject/opensearch:2.3.0
    restart: "unless-stopped"
    container_name: geonames-os
    environment:
      # settings only for development. DO NOT use in production!
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    ports:
      - "9200:9200"
      - "9600:9600"
  geonames-os-dashboard:
    image: opensearchproject/opensearch-dashboards:2.3.0
    restart: "unless-stopped"
    container_name: geonames-dashboard
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      # settings only for development. DO NOT use in production!
      - 'OPENSEARCH_HOSTS=["http://geonames-os:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
  geonames-cache:
    image: redis
    restart: "unless-stopped"
    container_name: geonames-cache
    read_only: true
    ports:
      - "6379:6379"
  geonames-service:
    image: geonames-search/api:v0.1.0
    build: .
    container_name: geonames-service
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/settings.toml:/app/settings.toml:ro
